[project]
name = "CaseByCase"
requires-python = ">=3.10"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true